- name: backend configuration
  hosts: backend
  become: yes
  vars:
   mysql_root_password: "ExpenseApp@1"
   mysql_host: "mysql.devteck.xyz"
  tasks:
  - name: disable the nodejs application
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable the nodejs:20 application
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs:20 app 
    ansible.builtin.package:
     name: "{{ item }}"
     state: present
    loop:
    - nodejs
    - mysql

  - name: install dependencies
    ansible.builtin.pip:
     name: PyMySQL
     state: present
  

  - name: add application user expense 
    ansible.builtin.user:
     name: expense

  - name: create app directory
    ansible.builtin.file:
     path: /app
     state: directory


  - name: downloading the application code
    ansible.builtin.get_url:
     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip 
     dest: /tmp/backend.zip


  - name: Extract the zip file into /app
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes
    
  - name: Execute a command in the app directory
    ansible.builtin.command:
      cmd: npm install
      chdir: /app

  - name: copy backend file to remote server
    ansible.builtin.copy:
     src: backend.service
     dest: /etc/systemd/system/backend.service

  - name: import mysql data to the database
    mysql_db:
     login_user: root
     login_password: "{{ mysql_root_password }}"
     login_host: "{{ mysql_host }}"
     state: import
     name: all
     target: /app/schema/backend.sqlp.sql

  - name: restart the service 
    ansible.builtin.systemd_service:
     state: restarted
     daemon_reload: true
     name: backend





   



