- name: mysql configuration
  hosts: mysql
  become: yes
  tasks:
  - name: mysql server installation
    ansible.builtin.package:
     name: mysql-server
     state: present

  - name: start ysql server
    ansible.builtin.service:
     name: mysqld
     state: started
     enabled: yes

  


